version: '3.3'
services:  
  db:
    container_name: postgresdb
    restart: always
    image: postgres  # Using the correct Docker Hub official image name
    volumes:
      - ./db/data/:/var/lib/postgresql/data
    env_file:
        - ./.env
    ports:
      - 5432:5432
    networks:
      - psql-pgql  

  graphql:
    container_name: dependex-graphql
    restart: always
    image: dependex-graphql
    build:
        context: ./graphql
    env_file:
        - ./.env
    depends_on:
        - db
    ports:
      - 5433:5433
    command:
      [
        "--connection",
        "${DATABASE_URL}",
        "--port",
        "5433",
        "--schema",
        "public",
        "--append-plugins",
        "postgraphile-plugin-connection-filter,custom-plugin",
      ]
    networks:
      - psql-pgql

networks:
  psql-pgql:

volumes:
  db: